### ISSUE TITLE
Remove snyk-protect command

### ISSUE THREAD

**Issue by mejiaj** [GSA-TTS/touchpoints-site#91]
When running `npm start` a message pops up in terminal. 

1. Update snyk
1. Remove snyk-protect scripts

USWDS-Site PR for reference - https://github.com/uswds/uswds-site/pull/1555.

```bash
⚠ WARNING: Starting from 31 March 2022, the protect command will be removed.
Please use the @snyk/protect package instead.
For more info: https://snyk.co/ueln7
```

**Comment by ryanwoldatwork** [comment]
thanks @mejiaj!
